import { Product } from "./product";

export const productData: Product[] = [
    {
      id: '1',
      name: "Product 1",
      price: 999.99,
      description: 'Very high quality product. Satisfaction guaranteed.',
      image: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',  
      creationDate: new Date(),
    },
    {
      id: '2',
      name: 'Product 2',
      price: 199.99,
      description: 'Bracelet made of silver',
      image: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
      creationDate: new Date(),
    },
    {
      id: '3',
      name: 'Product 3',
      price: 9.99,
      description: 'Beautiful diamond ring',
      image: 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg',
      creationDate: new Date(),
    },
    {
      id: '4',
      name: 'Product 4',
      price: 10.99,
      description: 'Rose Gold Plated Double ring',
      image: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
      creationDate: new Date(),
    },
    {
      id: '5',
      name: 'Product 5',
      price: 64.99,
      description: 'USB 3.0  black',
      image: 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg',
      creationDate: new Date(),
    },
    {
      id: '6',
      name: 'Product 6',
      price: 99.99,
      description: 'Sandisk Best flash drive',
      image: 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg',
      creationDate: new Date(),
    },
    {
      id: '7',
      name: 'Product 7',
      price: 56.99,
      description: 'Purple color with a beautiful design',
      image: 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg',
      creationDate: new Date(),
    },
    {
      id: '8',
      name: 'Product 8',
      price: 29.99,
      description: 'Red color with a beautiful design',
      image: 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg',
      creationDate: new Date(),
    },
    {
      id: '9',
      name: 'Product 9',
      price: 39.99,
      description: 'Striped Polo Shirt',
      image: 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg',
      creationDate: new Date(),
    },
    {
      id: '10',
      name: 'Product 10',
      price: 9.99,
      description: 'Beautiful shirt - great fit. Feel amazing in this shirt!',
      image: 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg',
      creationDate: new Date(),
    },
  ];